version: '3.9'

services:
  integration_tests:
    build:
      context: ../tests
      dockerfile: Dockerfile
    command: "true"
    environment:
      POSTGRES_HOST: "postgres"
    networks:
      - abs_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    networks:
      - abs_network

  ab_service:
    build:
      context: ../
      dockerfile: build/Dockerfile
    restart: always
    environment:
      loginLimit: 3
      passwordLimit: 3
      ipLimit: 3
      sqlHost: postgres
      sqlPort: 5432
      sqlDatabase: "postgres"
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    networks:
      - abs_network

networks:
  abs_network:

volumes:
  postgres-test-data:

