name: anti bruteforce service

on:
  push:
    branches:
      - main
      - master

env:
  GO111MODULE: "on"

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.19

      - name: Set GOROOT
        run: echo "GOROOT=$(go env GOROOT)" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v3

      - name: List directory contents
        run: ls -l

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: run --out-format=json .

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - name: Check out code
        uses: actions/checkout@v3

      - name: Unit tests
        run: go test -v -count=100 -race ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - name: Check out code
        uses: actions/checkout@v3

      - name: build
        run: go build -o service ./cmd